"""Information-preserving controlled Koopman flow map.

Final architecture used after the architecture-freeze diagnostics:

    X_t^v = Psi_theta(X_s,s,t; xi + v),       xi ~ N(0,I)
    E[r(X_t^v)|X_s] = A_{s,t} r(X_s) + J_{s,t} v + O(||v||^2).

The observable ``r`` is the validated frozen information anchor from the IP
Koopman model.  There is no learned lift and no pathwise Gaussian-affine model.
``A`` is generated by a general non-commuting piecewise-constant L(t), so its
finite-time composition is exact.  ``J`` is a global, horizon-specific response
tied to the *physical* Gaussian innovations used by the categorical sampler.

Stage-B generator gradients use a Gumbel-softmax surrogate, while all fitting
metrics, diagnostics, checkpoint gates, and final generation use the exact hard
sampler.  The surrogate is therefore an estimator, not a change to the scientific
model.
"""
from __future__ import annotations

import copy
import math
from dataclasses import asdict, dataclass, field
from typing import Any, Iterable, Mapping, Sequence

import torch
import torch.nn as nn
import torch.nn.functional as F

from .explicit_innovation import (
    normal_to_gumbel,
    sample_transition_with_gaussian_innovation,
    transition_innovation_layout,
)
from .ip_model import FrozenSharedLKFEncoder, InformationPreservingKoopmanLKF
from .lkf.uniform_lkf import UniformLKF, UniformLKFProcess

Tensor = torch.Tensor


def _as_tuple_float(value: Iterable[float]) -> tuple[float, ...]:
    return tuple(float(x) for x in value)


def _time_key(s: float, t: float) -> str:
    # Stable ParameterDict key; configured control knots are rounded to 6 decimals.
    return f"{float(s):.6f}_{float(t):.6f}".replace("-", "m").replace(".", "p")


@dataclass(frozen=True)
class ControlledKoopmanConfig:
    anchor_dim: int = 64
    anchor_seed: int = 60042
    feature_source: str = "shared_pooled_plus_time"
    operator_bins: int = 8
    operator_init_scale: float = 1e-3
    control_knots: tuple[float, ...] = field(
        default_factory=lambda: (0.0, 0.25, 0.5, 0.75, 1.0)
    )
    control_init_scale: float = 1e-3
    information_eigen_floor_relative: float = 1e-5
    information_epsilon: float = 1e-6
    soft_temperature: float = 0.5

    def __post_init__(self) -> None:
        if self.anchor_dim < 1:
            raise ValueError("anchor_dim must be >=1")
        if self.operator_bins < 1:
            raise ValueError("operator_bins must be >=1")
        if self.operator_init_scale < 0 or self.control_init_scale < 0:
            raise ValueError("initialization scales must be nonnegative")
        if self.feature_source not in {"shared_pooled_plus_time", "shared_pooled"}:
            raise ValueError("unsupported feature_source")
        knots = tuple(float(x) for x in self.control_knots)
        if len(knots) < 2 or knots[0] < 0 or knots[-1] > 1:
            raise ValueError("control_knots must contain >=2 values inside [0,1]")
        if any(b <= a for a, b in zip(knots, knots[1:])):
            raise ValueError("control_knots must be strictly increasing")
        if self.information_eigen_floor_relative < 0 or self.information_epsilon <= 0:
            raise ValueError("invalid information metric settings")
        if self.soft_temperature <= 0:
            raise ValueError("soft_temperature must be positive")

    def to_dict(self) -> dict[str, Any]:
        out = asdict(self)
        out["control_knots"] = list(self.control_knots)
        return out

    @classmethod
    def from_mapping(cls, value: Mapping[str, Any]) -> "ControlledKoopmanConfig":
        valid = set(asdict(cls()).keys())
        kwargs = {k: value[k] for k in valid if k in value}
        if "control_knots" in kwargs:
            kwargs["control_knots"] = _as_tuple_float(kwargs["control_knots"])
        return cls(**kwargs)


class ControlledKoopmanFlowMap(nn.Module):
    """Uniform-LKF + frozen information anchor + (A,J) controlled Koopman model."""

    def __init__(
        self,
        lkf: UniformLKF,
        config: ControlledKoopmanConfig,
        *,
        anchor_encoder: FrozenSharedLKFEncoder | None = None,
        anchor_projection: Tensor | None = None,
    ):
        super().__init__()
        self.lkf = lkf
        self.config = config

        if anchor_encoder is None:
            anchor_encoder = FrozenSharedLKFEncoder(
                lkf, feature_source=config.feature_source
            )
        self.anchor_encoder = copy.deepcopy(anchor_encoder)
        for p in self.anchor_encoder.parameters():
            p.requires_grad_(False)
        self.anchor_encoder.eval()

        d_in = int(lkf.model_dim)
        if anchor_projection is None:
            gen = torch.Generator(device="cpu")
            gen.manual_seed(int(config.anchor_seed))
            projection = torch.randn(
                d_in, int(config.anchor_dim), generator=gen, dtype=torch.float32
            ) / math.sqrt(float(config.anchor_dim))
        else:
            projection = torch.as_tensor(anchor_projection, dtype=torch.float32).detach().clone()
            if projection.shape != (d_in, int(config.anchor_dim)):
                raise ValueError(
                    f"anchor_projection must be {(d_in, int(config.anchor_dim))}, "
                    f"got {tuple(projection.shape)}"
                )
        self.register_buffer("anchor_projection", projection, persistent=True)

        d = int(config.anchor_dim)
        self.operator_generators = nn.Parameter(
            torch.empty(int(config.operator_bins), d, d, dtype=torch.float32)
        )
        nn.init.normal_(
            self.operator_generators,
            mean=0.0,
            std=float(config.operator_init_scale),
        )

        max_layout = transition_innovation_layout(
            UniformLKFProcess(lkf), int(lkf.seq_len)
        )
        self.max_innovation_dim = int(max_layout.total_dim)
        responses: dict[str, nn.Parameter] = {}
        knots = tuple(float(x) for x in config.control_knots)
        for i, s in enumerate(knots[:-1]):
            for t in knots[i + 1 :]:
                p = nn.Parameter(
                    torch.empty(d, self.max_innovation_dim, dtype=torch.float32)
                )
                nn.init.normal_(p, mean=0.0, std=float(config.control_init_scale))
                responses[_time_key(s, t)] = p
        self.control_responses = nn.ParameterDict(responses)
        # Streaming sufficient-statistic counts for Stage-A global Stein J.
        # Counts are per physical innovation column because token length may vary.
        self._control_response_keys = tuple(responses.keys())
        self.register_buffer(
            "control_response_counts",
            torch.zeros(len(self._control_response_keys), self.max_innovation_dim, dtype=torch.float64),
            persistent=True,
        )

        # Fixed calibration geometry.  Identity is used only until Stage-A
        # calibration initializes the buffer; checkpoints always persist it.
        self.register_buffer("information_transform", torch.eye(d), persistent=True)
        self.register_buffer("information_covariance", torch.eye(d), persistent=True)
        self.register_buffer("information_eigenvalues", torch.ones(d), persistent=True)
        self.register_buffer("information_rank", torch.tensor(d, dtype=torch.long), persistent=True)
        self.register_buffer("information_metric_initialized", torch.tensor(False), persistent=True)

    @classmethod
    def from_ip_model(
        cls,
        ip_model: InformationPreservingKoopmanLKF,
        config: ControlledKoopmanConfig | None = None,
    ) -> "ControlledKoopmanFlowMap":
        """Initialize active generator + frozen validated anchor from an IP checkpoint."""
        if config is None:
            config = ControlledKoopmanConfig(
                anchor_dim=int(ip_model.anchor_dim),
                anchor_seed=int(ip_model.config.anchor_seed),
                feature_source=str(ip_model.config.feature_source),
            )
        if int(config.anchor_dim) != int(ip_model.anchor_dim):
            raise ValueError("controlled anchor_dim must match validated IP anchor_dim")
        return cls(
            ip_model.lkf,
            config,
            anchor_encoder=ip_model.anchor_encoder,
            anchor_projection=ip_model.anchor_projection,
        )

    @property
    def anchor_dim(self) -> int:
        return int(self.config.anchor_dim)

    @property
    def process(self) -> UniformLKFProcess:
        return UniformLKFProcess(self.lkf)

    def train(self, mode: bool = True):
        super().train(mode)
        # The reference anchor is immutable even while the active generator is trained.
        self.anchor_encoder.eval()
        return self

    @torch.no_grad()
    def anchor_features(self, x: Tensor, time: float | Tensor) -> Tensor:
        self.lkf.validate_peptide_tokens(x, name="controlled_anchor_x")
        hidden = self.anchor_encoder(x, time)
        return hidden.float() @ self.anchor_projection.float()

    def _anchor_from_soft_residue_probs(self, probs: Tensor, time: float | Tensor) -> Tensor:
        """Differentiable frozen-anchor surrogate from soft canonical-AA tokens.

        ``probs`` has shape [B,L-2,A] over the LKF canonical AA ordering.  Anchor
        parameters stay frozen but gradients flow to ``probs`` and therefore to
        the active generator and control intervention.
        """
        if probs.ndim != 3:
            raise ValueError("probs must be [B,L-2,A]")
        b, residues, aa_count = probs.shape
        aa_ids = torch.tensor(
            self.lkf.config.aa_token_ids, device=probs.device, dtype=torch.long
        )
        if aa_count != int(aa_ids.numel()):
            raise ValueError("soft AA dimension does not match LKF canonical AA count")
        enc = self.anchor_encoder
        emb = enc.token_embedder.weight
        aa_emb = emb.index_select(0, aa_ids).float()
        interior = probs.float() @ aa_emb
        cls = emb[int(self.lkf.config.cls_token_id)].float().view(1, 1, -1).expand(b, 1, -1)
        eos = emb[int(self.lkf.config.eos_token_id)].float().view(1, 1, -1).expand(b, 1, -1)
        hidden = torch.cat([cls, interior, eos], dim=1)
        length = residues + 2
        t = torch.as_tensor(time, device=probs.device, dtype=enc.pos_embedder.dtype)
        if t.ndim == 0:
            t = t.expand(b)
        elif t.ndim == 1 and t.shape[0] == b:
            pass
        else:
            raise ValueError("time must be scalar or [batch]")
        condition = enc.time_embedder(t)
        hidden = hidden + enc.pos_embedder[:, :length]
        for block in enc.shared_blocks:
            hidden = block(hidden, condition)
        pooled = hidden[:, 1:-1].mean(dim=1)
        if self.config.feature_source == "shared_pooled_plus_time":
            pooled = pooled + condition
        return pooled.float() @ self.anchor_projection.float()

    def soft_controlled_anchor_samples(
        self,
        x_s: Tensor,
        s: float,
        t: float,
        *,
        xi: Tensor,
        mean_shift: Tensor | None = None,
        temperature: float | None = None,
    ) -> Tensor:
        """Differentiable Gumbel-softmax anchor samples for Stage-B gradients.

        This method is never used for diagnostics or final generation.  It uses
        exactly the same transition logits and Gaussian->Gumbel noises as the
        hard physical sampler, replacing only argmax by softmax.
        """
        self.lkf.validate_peptide_tokens(x_s, name="soft_control_x_s")
        if x_s.device != next(self.parameters()).device:
            raise ValueError("x_s must be on model device")
        b, length = x_s.shape
        process = UniformLKFProcess(self.lkf)
        layout = transition_innovation_layout(process, length)
        xi = torch.as_tensor(xi, device=x_s.device, dtype=torch.float32)
        if xi.shape != (b, layout.total_dim):
            raise ValueError(
                f"xi must be {(b, layout.total_dim)}, got {tuple(xi.shape)}"
            )
        used = xi
        if mean_shift is not None:
            shift = torch.as_tensor(mean_shift, device=x_s.device, dtype=torch.float32)
            if shift.ndim == 1:
                shift = shift.unsqueeze(0)
            if shift.shape[1] != layout.total_dim or shift.shape[0] not in (1, b):
                raise ValueError("mean_shift has incompatible shape")
            used = used + shift

        sb = process._times(float(s), b, name="s")
        tb = process._times(float(t), b, name="t")
        log_router, token_logp = process._component_transition_log_probs(x_s, sb, tb)
        router_xi = used[:, : layout.router_dim]
        token_xi = used[:, layout.router_dim :].reshape(
            b, layout.residue_positions, layout.amino_acids
        )
        tau = float(temperature if temperature is not None else self.config.soft_temperature)
        router_prob = F.softmax(
            (log_router.float() + normal_to_gumbel(router_xi)) / tau, dim=-1
        )  # [B,M]
        token_g = normal_to_gumbel(token_xi)[:, None, :, :]  # [B,1,L,A]
        token_prob_by_latent = F.softmax(
            (token_logp.float() + token_g) / tau, dim=-1
        )
        residue_prob = torch.einsum("bm,bmla->bla", router_prob, token_prob_by_latent)
        return self._anchor_from_soft_residue_probs(residue_prob, float(t))

    def initialize_information_metric(
        self,
        covariance: Tensor,
        *,
        eigen_floor_relative: float | None = None,
        epsilon: float | None = None,
    ) -> dict[str, float]:
        """Freeze C_r and T_r=(Q^T C Q + eps I)^-1/2 Q^T on stable modes."""
        cov = torch.as_tensor(covariance, dtype=torch.float64, device=self.anchor_projection.device)
        if cov.shape != (self.anchor_dim, self.anchor_dim):
            raise ValueError("covariance has wrong shape")
        cov = 0.5 * (cov + cov.T)
        eig, q = torch.linalg.eigh(cov)
        eig = eig.clamp_min(0)
        max_eig = eig.max().clamp_min(1e-30)
        floor_rel = float(
            self.config.information_eigen_floor_relative
            if eigen_floor_relative is None
            else eigen_floor_relative
        )
        mask = eig >= floor_rel * max_eig
        if not bool(mask.any()):
            mask[eig.argmax()] = True
        eig_keep = eig[mask]
        q_keep = q[:, mask]
        eps = float(self.config.information_epsilon if epsilon is None else epsilon)
        transform = torch.diag(torch.rsqrt(eig_keep + eps)) @ q_keep.T

        # Buffers may change first dimension; direct replacement remains registered.
        self.information_transform = transform.float()
        self.information_covariance = cov.float()
        self.information_eigenvalues = eig.float()
        self.information_rank = torch.tensor(int(mask.sum().item()), device=cov.device, dtype=torch.long)
        self.information_metric_initialized = torch.tensor(True, device=cov.device)
        return {
            "information_rank": float(mask.sum().item()),
            "cov_min_eigenvalue": float(eig_keep.min().item()),
            "cov_max_eigenvalue": float(eig_keep.max().item()),
            "floor_relative": floor_rel,
        }

    def information_normalize(self, value: Tensor) -> Tensor:
        t = self.information_transform.float()
        if value.shape[-1] != self.anchor_dim:
            raise ValueError("last dimension must be anchor_dim")
        return value.float() @ t.T

    def _operator_scalar(self, s: float, t: float) -> Tensor:
        if not (0.0 <= float(s) <= float(t) <= 1.0):
            raise ValueError("operator requires 0<=s<=t<=1")
        d = self.anchor_dim
        device = self.operator_generators.device
        dtype = self.operator_generators.dtype
        if math.isclose(float(s), float(t), rel_tol=0.0, abs_tol=1e-12):
            return torch.eye(d, device=device, dtype=dtype)
        bins = int(self.config.operator_bins)
        width = 1.0 / float(bins)
        A = torch.eye(d, device=device, dtype=dtype)
        # Column-vector convention: z_t=A z_s.  Later segments multiply on left.
        for k in range(bins):
            lo, hi = k * width, (k + 1) * width
            overlap = max(0.0, min(float(t), hi) - max(float(s), lo))
            if overlap <= 0:
                continue
            E = torch.matrix_exp(float(overlap) * self.operator_generators[k].float())
            A = E @ A
        return A

    def operator(self, s: float | Tensor, t: float | Tensor) -> Tensor:
        s_t = torch.as_tensor(s)
        t_t = torch.as_tensor(t)
        if s_t.ndim == 0 and t_t.ndim == 0:
            return self._operator_scalar(float(s_t.item()), float(t_t.item()))
        s_b, t_b = torch.broadcast_tensors(s_t.float(), t_t.float())
        mats = [self._operator_scalar(float(a), float(b)) for a, b in zip(s_b.reshape(-1), t_b.reshape(-1))]
        return torch.stack(mats, dim=0).reshape(*s_b.shape, self.anchor_dim, self.anchor_dim)

    def predict_uncontrolled_mean(self, r_s: Tensor, s: float, t: float) -> Tensor:
        A = self.operator(float(s), float(t))
        return r_s.float() @ A.T

    def _match_control_pair(self, s: float, t: float, tol: float = 1e-6) -> tuple[float, float]:
        knots = tuple(float(x) for x in self.config.control_knots)
        ss = min(knots, key=lambda x: abs(x - float(s)))
        tt = min(knots, key=lambda x: abs(x - float(t)))
        if abs(ss - float(s)) > tol or abs(tt - float(t)) > tol or not ss < tt:
            raise KeyError(
                f"J is defined only on configured control knots {knots}; requested ({s},{t})"
            )
        return ss, tt

    def control_response_index(self, s: float, t: float) -> int:
        ss, tt = self._match_control_pair(float(s), float(t))
        key = _time_key(ss, tt)
        return self._control_response_keys.index(key)

    def control_response(self, s: float, t: float, *, token_length: int | None = None) -> Tensor:
        ss, tt = self._match_control_pair(float(s), float(t))
        J = self.control_responses[_time_key(ss, tt)].float()
        if token_length is None:
            return J
        layout = transition_innovation_layout(UniformLKFProcess(self.lkf), int(token_length))
        return J[:, : int(layout.total_dim)]

    def aggregate_response(self, chain: Sequence[float], *, token_length: int) -> Tensor:
        times = tuple(float(x) for x in chain)
        if len(times) < 2 or any(b <= a for a, b in zip(times, times[1:])):
            raise ValueError("chain must be strictly increasing with at least two times")
        T = times[-1]
        blocks: list[Tensor] = []
        for s, t in zip(times[:-1], times[1:]):
            J = self.control_response(s, t, token_length=token_length)
            Aprop = self.operator(t, T)
            blocks.append(Aprop @ J)
        return torch.cat(blocks, dim=1)

    def gramian(
        self,
        chain: Sequence[float],
        *,
        token_length: int,
        normalized: bool = False,
    ) -> Tensor:
        M = self.aggregate_response(chain, token_length=token_length)
        G = M @ M.T
        if normalized:
            T = self.information_transform.float()
            G = T @ G @ T.T
        return 0.5 * (G + G.T)

    @torch.no_grad()
    def semigroup_error(self, s: float, u: float, t: float) -> float:
        direct = self.operator(s, t)
        composed = self.operator(u, t) @ self.operator(s, u)
        den = torch.linalg.norm(direct).clamp_min(1e-12)
        return float((torch.linalg.norm(direct - composed) / den).item())

    def sample_transition(
        self,
        x_s: Tensor,
        s: float,
        t: float,
        *,
        xi: Tensor | None = None,
        mean_shift: Tensor | None = None,
        generator: torch.Generator | None = None,
        return_latent: bool = False,
    ):
        return sample_transition_with_gaussian_innovation(
            UniformLKFProcess(self.lkf),
            x_s,
            float(s),
            float(t),
            xi=xi,
            mean_shift=mean_shift,
            generator=generator,
            return_latent=return_latent,
        )

    def auxiliary_state_dict(self) -> dict[str, Tensor]:
        return {k: v for k, v in self.state_dict().items() if not k.startswith("lkf.")}

    def load_auxiliary_state_dict(self, state: Mapping[str, Tensor], *, strict: bool = True) -> None:
        # The retained information subspace may have rank < anchor_dim, so the
        # persisted information_transform can have a different leading dimension
        # from the constructor placeholder. Resize registered buffers first.
        for name in ("information_transform", "information_covariance", "information_eigenvalues",
                     "information_rank", "information_metric_initialized"):
            if name in state:
                setattr(self, name, torch.as_tensor(state[name]).detach().clone())
        current = self.state_dict()
        merged = dict(current)
        for key, value in state.items():
            if key.startswith("lkf."):
                raise ValueError("auxiliary state must not contain lkf.* keys")
            if key not in merged:
                if strict:
                    raise KeyError(f"unexpected controlled-Koopman state key: {key}")
                continue
            merged[key] = value
        expected = {k for k in current if not k.startswith("lkf.")}
        missing = expected.difference(state.keys())
        # v2 checkpoints predate streaming Stein sufficient-statistic counts.
        # Missing counts are safely initialized to zero on migration.
        missing.discard("control_response_counts")
        if strict and missing:
            raise KeyError(f"missing controlled-Koopman keys: {sorted(missing)[:8]}")
        self.load_state_dict(merged, strict=True)
        self.anchor_encoder.eval()


def configure_controlled_trainability(
    model: ControlledKoopmanFlowMap,
    *,
    stage: str,
    unfreeze_shared_blocks: int = 2,
    unfreeze_downstream: bool = True,
) -> list[str]:
    """Stage A: only A/J.  Stage B: A/J + conservative active-LKF tail."""
    from .model import configure_lkf_trainability

    stage = str(stage).upper()
    for p in model.parameters():
        p.requires_grad_(False)
    model.operator_generators.requires_grad_(True)
    for p in model.control_responses.parameters():
        p.requires_grad_(stage != "A")
    if stage == "A":
        model.lkf.eval()
        model.anchor_encoder.eval()
        return []
    if stage != "B":
        raise ValueError("stage must be A or B")
    names = configure_lkf_trainability(
        model.lkf,
        stage="B",
        unfreeze_shared_blocks=int(unfreeze_shared_blocks),
        unfreeze_downstream=bool(unfreeze_downstream),
    )
    model.anchor_encoder.eval()
    return names


__all__ = [
    "ControlledKoopmanConfig",
    "ControlledKoopmanFlowMap",
    "configure_controlled_trainability",
]
